name: 更新美国节点


on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:

  update-us:

    runs-on: ubuntu-latest

    env:
      ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}

    steps:

      - name: 获取代码
        uses: actions/checkout@v4


      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"


      - name: 安装依赖
        run: |
          pip install -r requirements.txt


      - name: 执行美国节点筛选
        run: |
          python filter-us.py


      - name: 提交更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git commit -m "自动更新美国节点 $(date '+%Y-%m-%d %H:%M')" || exit 0

          git push
